
import type { Question } from '../types';

const quizData = {
    "part1": [
        { "id": "p1q1", "type": "single-select", "question": { "en": "In the EPSON robot model series, Which series is not in the EPSON 6-AxisPro.", "vi": "Trong dòng model robot EPSON, dòng nào không thuộc EPSON 6-AxisPro." }, "options": [ { "en": "C series", "vi": "Dòng C" }, { "en": "VT series", "vi": "Dòng VT" }, { "en": "S5 series", "vi": "Dòng S5" }, { "en": "G series", "vi": "Dòng G" } ], "correctAnswers": [3], "explanation": { "en": "G series is a SCARA robot series (4-axis), not a 6-axis robot.", "vi": "Dòng G là dòng robot SCARA (4 trục), không phải robot 6 trục." } },
        { "id": "p1q2", "type": "single-select", "question": { "en": "Which robot has the longest arm?", "vi": "Robot nào có cánh tay dài nhất?" }, "options": [ { "en": "S-901S", "vi": "S-901S" }, { "en": "S-A600S", "vi": "S-A600S" }, { "en": "S-700S", "vi": "S-700S" }, { "en": "C12XL 6-Axis Robot", "vi": "Robot 6 trục C12XL" } ], "correctAnswers": [3], "explanation": { "en": "The C12XL 6-Axis Robot has an arm length of 1400mm.", "vi": "Robot 6 trục C12XL có chiều dài cánh tay là 1400mm." } },
        { "id": "p1q3", "type": "single-select", "question": { "en": "Which company does not make industrial robot arms?", "vi": "Công ty nào không sản xuất cánh tay robot công nghiệp?" }, "options": [ { "en": "ABB Ltd.", "vi": "ABB Ltd." }, { "en": "Fanuc Corp.", "vi": "Fanuc Corp." }, { "en": "iRobot", "vi": "iRobot" }, { "en": "Epson Robots", "vi": "Epson Robots" } ], "correctAnswers": [2], "explanation": { "en": "iRobot is known for consumer robots like the Roomba vacuum cleaner, not industrial arms.", "vi": "iRobot được biết đến với các robot tiêu dùng như máy hút bụi Roomba, không phải là tay máy công nghiệp." } },
        { "id": "p1q4", "type": "multi-select", "question": { "en": "What components are included in the work cell of the robotic exercise platform? (Multi-selection)", "vi": "Những thành phần nào được bao gồm trong ô làm việc của nền tảng thực hành robot? (Chọn nhiều)" }, "options": [ { "en": "Feeder cell", "vi": "Ô cấp phôi" }, { "en": "Tray", "vi": "Khay" }, { "en": "Fixture", "vi": "Đồ gá" }, { "en": "Reference pole (rod)", "vi": "Cọc tham chiếu" } ], "correctAnswers": [0, 1, 2, 3], "explanation": { "en": "All listed components are part of the work cell for the exercises.", "vi": "Tất cả các thành phần được liệt kê đều là một phần của ô làm việc cho các bài thực hành." } },
        { "id": "p1q5", "type": "multi-select", "question": { "en": "Which end-effectors are excluded from the exercises? (Multi-selection)", "vi": "Những dụng cụ đầu cuối nào không được sử dụng trong các bài thực hành? (Chọn nhiều)" }, "options": [ { "en": "Gripper", "vi": "Tay kẹp" }, { "en": "Vacuum nozzle", "vi": "Đầu hút chân không" }, { "en": "Electrical Screwdriver", "vi": "Tua vít điện" }, { "en": "Torch", "vi": "Mỏ hàn" }, { "en": "Soldering gun", "vi": "Súng hàn thiếc" }, { "en": "Glue gun", "vi": "Súng bắn keo" } ], "correctAnswers": [2, 3, 4, 5], "explanation": { "en": "The exercises primarily use grippers and vacuum nozzles. Other tools like screwdrivers, torches, soldering guns, and glue guns are not used.", "vi": "Các bài thực hành chủ yếu sử dụng tay kẹp và đầu hút chân không. Các công cụ khác như tua vít, mỏ hàn, súng hàn và súng bắn keo không được sử dụng." } },
        { "id": "p1q6", "type": "single-select", "question": { "en": "What protocol is not the main one for the communication between the PC to the EPSON robot?", "vi": "Giao thức nào không phải là giao thức chính để giao tiếp giữa PC và robot EPSON?" }, "options": [ { "en": "Fieldbus", "vi": "Fieldbus" }, { "en": "USB port", "vi": "Cổng USB" }, { "en": "Ethernet", "vi": "Ethernet" }, { "en": "WiFi", "vi": "WiFi" } ], "correctAnswers": [0], "explanation": { "en": "USB and Ethernet are the primary direct communication methods. WiFi is generally not used for stability reasons. Fieldbus is a communication system, but not the primary PC-to-robot link.", "vi": "USB và Ethernet là các phương thức giao tiếp trực tiếp chính. WiFi thường không được sử dụng vì lý do ổn định. Fieldbus là một hệ thống giao tiếp, nhưng không phải là liên kết chính từ PC đến robot." } },
        { "id": "p1q7", "type": "multi-select", "question": { "en": "Which description below is not true regarding the RC180 controller?", "vi": "Mô tả nào dưới đây không đúng về bộ điều khiển RC180?" }, "options": [ { "en": "RC180 possessed embedded 50-pin i/o bus", "vi": "RC180 sở hữu bus I/O 50 chân tích hợp" }, { "en": "RC180 does not have any external ports.", "vi": "RC180 không có bất kỳ cổng ngoại vi nào." }, { "en": "Emergency Stop I/O cannot be used for general purpose", "vi": "I/O Dừng khẩn cấp không thể được sử dụng cho mục đích chung" }, { "en": "Can connect either NPN or PNP sensors, but not simultaneously.", "vi": "Có thể kết nối cảm biến NPN hoặc PNP, nhưng không thể đồng thời." } ], "correctAnswers": [1, 2, 3], "explanation": { "en": "RC180 does have external ports (USB, Ethernet). The Emergency Stop I/O can be used for general purposes, and it supports both NPN and PNP sensors simultaneously.", "vi": "RC180 có các cổng ngoại vi (USB, Ethernet). I/O Dừng khẩn cấp có thể được sử dụng cho các mục đích chung, và nó hỗ trợ cả cảm biến NPN và PNP đồng thời." } },
        { "id": "p1q8", "type": "multi-select", "question": { "en": "In a pneumatic system, which component connects to the I/O port and is driven by electricity? (multi-selection)", "vi": "Trong hệ thống khí nén, thành phần nào kết nối với cổng I/O và được điều khiển bằng điện? (chọn nhiều)" }, "options": [ { "en": "Solenoid", "vi": "Van điện từ (Solenoid)" }, { "en": "Vacuum filter", "vi": "Bộ lọc chân không" }, { "en": "Cylinder", "vi": "Xy lanh" }, { "en": "Gripper", "vi": "Tay kẹp" }, { "en": "Pressure gauge", "vi": "Đồng hồ đo áp suất" }, { "en": "Silencer", "vi": "Giảm thanh" }, { "en": "Vacuum generator", "vi": "Bộ tạo chân không" } ], "correctAnswers": [0], "explanation": { "en": "The solenoid valve is an electromechanical component that uses an electrical signal from the I/O port to control air flow.", "vi": "Van điện từ là một thành phần cơ điện sử dụng tín hiệu điện từ cổng I/O để điều khiển luồng không khí." } },
        { "id": "p1q9", "type": "single-select", "question": { "en": "Which pneumatic component is not included in the work cell of our class?", "vi": "Thành phần khí nén nào không có trong ô làm việc của lớp chúng ta?" }, "options": [ { "en": "Pressure gauge", "vi": "Đồng hồ đo áp suất" }, { "en": "Solenoid", "vi": "Van điện từ" }, { "en": "Vacuum Filter", "vi": "Bộ lọc chân không" }, { "en": "Rotary cylinder", "vi": "Xy lanh quay" } ], "correctAnswers": [3], "explanation": { "en": "The standard work cell setup does not include a rotary cylinder.", "vi": "Thiết lập ô làm việc tiêu chuẩn không bao gồm một xy lanh quay." } },
        { "id": "p1q10", "type": "single-select", "question": { "en": "What tasks should I complete in the class?", "vi": "Tôi nên hoàn thành những nhiệm vụ nào trong lớp?" }, "options": [ { "en": "Exercise #1: Calibration and Alignment", "vi": "Bài tập #1: Hiệu chuẩn và Căn chỉnh" }, { "en": "Exercise #2: I/O and port communication", "vi": "Bài tập #2: Giao tiếp I/O và cổng" }, { "en": "Final exercise: with challenging tasks", "vi": "Bài tập cuối kỳ: với các nhiệm vụ thách thức" }, { "en": "Create a repository at Github as the collaborative platform for the team to keep all data in the class", "vi": "Tạo một kho lưu trữ tại Github làm nền tảng hợp tác cho nhóm để lưu giữ tất cả dữ liệu trong lớp" }, { "en": "Design mechanical parts and print them with a 3D printer", "vi": "Thiết kế các bộ phận cơ khí và in chúng bằng máy in 3D" }, { "en": "Illustrate the wiring diagram connecting the I/O box to the Robot I/O port.", "vi": "Minh họa sơ đồ đi dây kết nối hộp I/O với cổng I/O của Robot." }, { "en": "All of the above", "vi": "Tất cả các câu trên" } ], "correctAnswers": [6], "explanation": { "en": "All of the listed tasks are part of the course requirements.", "vi": "Tất cả các nhiệm vụ được liệt kê là một phần của yêu cầu khóa học." } }
    ],
    "part2": [
        { "id": "p2q1", "type": "single-select", "image": "https://i.postimg.cc/T3tGC1xP/1-partII.png", "alt": { "en": "RC180 controller back panel", "vi": "Mặt sau bộ điều khiển RC180" }, "question": { "en": "Which components/sockets/connector name below is not correct?", "vi": "Tên thành phần/ổ cắm/đầu nối nào dưới đây không đúng?" }, "options": [ { "en": "A. Power Switch (On/Off)", "vi": "A. Công tắc nguồn (Bật/Tắt)" }, { "en": "B. 50-pin I/O connector", "vi": "B. Đầu nối I/O 50 chân" }, { "en": "C. Emergency Stop", "vi": "C. Dừng khẩn cấp" }, { "en": "D. Expansion I/O terminal", "vi": "D. Cổng I/O mở rộng" } ], "correctAnswers": [3], "explanation": { "en": "D points to the MC (Manipulator Connector) port, not the Expansion I/O terminal.", "vi": "D chỉ vào cổng MC (Đầu nối tay máy), không phải cổng I/O mở rộng." } },
        { "id": "p2q2", "type": "single-select", "question": { "en": "About the EPSON Robot model numbering – C4-A901S, which statement is not correct.", "vi": "Về cách đánh số model Robot EPSON – C4-A901S, nhận định nào không đúng." }, "options": [ { "en": "A – Series.", "vi": "A – Dòng." }, { "en": "9 – load.", "vi": "9 – tải trọng." }, { "en": "0 – arm length.", "vi": "0 – chiều dài tay." }, { "en": "1 – Axis brake.", "vi": "1 – Phanh trục." }, { "en": "S – SLAM", "vi": "S – SLAM" } ], "correctAnswers": [4], "explanation": { "en": "'S' in the model number typically indicates the installation environment, such as Standard or Cleanroom, not SLAM.", "vi": "'S' trong số model thường chỉ môi trường lắp đặt, chẳng hạn như Tiêu chuẩn hoặc Phòng sạch, không phải SLAM." } },
        { "id": "p2q3", "type": "single-select", "question": { "en": "In a floor-mounted robot’s configuration, the “right-hand rule” is an easy way to recognize the World frame orientation in space. What statement below is incorrect?", "vi": "Trong cấu hình robot gắn trên sàn, 'quy tắc bàn tay phải' là một cách dễ dàng để nhận biết hướng của hệ tọa độ World trong không gian. Nhận định nào dưới đây không chính xác?" }, "options": [ { "en": "Pointer finger (or index finger) – X axis.", "vi": "Ngón trỏ – trục X." }, { "en": "Middle finger – Y axis.", "vi": "Ngón giữa – trục Y." }, { "en": "Thumb – Z axis.", "vi": "Ngón cái – trục Z." }, { "en": "@Local frame – Axis brake.", "vi": "Hệ tọa độ @Local – Phanh trục." }, { "en": "@Tool frame – J6 Tool mount", "vi": "Hệ tọa độ @Tool – Ngàm công cụ J6" } ], "correctAnswers": [4], "explanation": { "en": "The @Tool frame is relative to the tool attached to the J6 flange, it's not the mount itself.", "vi": "Hệ tọa độ @Tool có liên quan đến công cụ được gắn vào mặt bích J6, nó không phải là chính ngàm gắn." } },
        { "id": "p2q4", "type": "single-select", "question": { "en": "What description below is incorrect?", "vi": "Mô tả nào dưới đây không chính xác?" }, "options": [ { "en": "Local 0 is also called World coordinate to a robot", "vi": "Local 0 còn được gọi là hệ tọa độ World của robot" }, { "en": "Tool 0 can not be changed", "vi": "Tool 0 không thể thay đổi" }, { "en": "With RC-180, 24 local coordinates and 16 tool coordinates are available.", "vi": "Với RC-180, có sẵn 24 hệ tọa độ local và 16 hệ tọa độ tool." }, { "en": "Release the E-Stop before turning on the robot controller.", "vi": "Nhả nút Dừng khẩn cấp trước khi bật bộ điều khiển robot." } ], "correctAnswers": [2], "explanation": { "en": "With RC-180, there are 16 local coordinates and 16 tool coordinates available, not 24 local coordinates.", "vi": "Với RC-180, có sẵn 16 hệ tọa độ local và 16 hệ tọa độ tool, không phải 24 hệ tọa độ local." } },
        { "id": "p2q5", "type": "single-select", "question": { "en": "The “J” in the “JTran” command represents __________.", "vi": "Chữ 'J' trong lệnh 'JTran' đại diện cho __________." }, "options": [ { "en": "Joint", "vi": "Khớp (Joint)" }, { "en": "Jump", "vi": "Nhảy (Jump)" }, { "en": "Jogging", "vi": "Chạy Gá (Jogging)" }, { "en": "J-Type connector", "vi": "Đầu nối loại J" } ], "correctAnswers": [0], "explanation": { "en": "JTran stands for Joint Translation, a command to move a specific robot joint.", "vi": "JTran là viết tắt của Joint Translation (Dịch chuyển khớp), một lệnh để di chuyển một khớp robot cụ thể." } },
        { "id": "p2q6", "type": "single-select", "question": { "en": "Choice the correct description for “TGo” and “BGo”", "vi": "Chọn mô tả đúng cho “TGo” và “BGo”" }, "options": [ { "en": "T means Tool coordinate.", "vi": "T có nghĩa là tọa độ Tool." }, { "en": "B means Base coordinate.", "vi": "B có nghĩa là tọa độ Base." }, { "en": "The answers in A and B both are correct.", "vi": "Các câu trả lời trong A và B đều đúng." }, { "en": "No correct answer.", "vi": "Không có câu trả lời đúng." } ], "correctAnswers": [2], "explanation": { "en": "TGo uses Tool coordinates for movement, and BGo uses Base (World/Local) coordinates.", "vi": "TGo sử dụng tọa độ Tool để di chuyển, và BGo sử dụng tọa độ Base (World/Local)." } },
        { "id": "p2q7", "type": "single-select", "question": { "en": "What’s the meaning of “Here”", "vi": "“Here” có nghĩa là gì" }, "options": [ { "en": "Current Flange-End to World coordinate", "vi": "Tọa độ hiện tại của mặt bích cuối so với hệ tọa độ World" }, { "en": "The last executed point of the local", "vi": "Điểm thực thi cuối cùng của hệ tọa độ local" }, { "en": "Point of Home", "vi": "Điểm Home" }, { "en": "Original point of current coordinate", "vi": "Điểm gốc của hệ tọa độ hiện tại" } ], "correctAnswers": [0], "explanation": { "en": "The 'Here' command returns the current position and orientation of the robot's tool flange center relative to the World coordinate system.", "vi": "Lệnh 'Here' trả về vị trí và hướng hiện tại của tâm mặt bích công cụ của robot so với hệ tọa độ World." } },
        { "id": "p2q8", "type": "single-select", "question": { "en": "Which description is correct about standard I/O?", "vi": "Mô tả nào đúng về I/O tiêu chuẩn?" }, "options": [ { "en": "The output voltage is 110 volts.", "vi": "Điện áp đầu ra là 110 volt." }, { "en": "There are 24 input signals (DI).", "vi": "Có 24 tín hiệu đầu vào (DI)." }, { "en": "There are 24 output signals (DO).", "vi": "Có 24 tín hiệu đầu ra (DO)." }, { "en": "The I/O connector is a D-sub 25-pin.", "vi": "Đầu nối I/O là D-sub 25 chân." } ], "correctAnswers": [1], "explanation": { "en": "The standard I/O on the RC180 controller has 24 digital inputs and 16 digital outputs.", "vi": "I/O tiêu chuẩn trên bộ điều khiển RC180 có 24 đầu vào kỹ thuật số và 16 đầu ra kỹ thuật số." } },
        { "id": "p2q9", "type": "single-select", "question": { "en": "What message is not included in the LED display of the I/O controller (RC180)?", "vi": "Thông báo nào không được bao gồm trong màn hình LED của bộ điều khiển I/O (RC180)?" }, "options": [ { "en": "Error", "vi": "Lỗi" }, { "en": "Warning", "vi": "Cảnh báo" }, { "en": "Emergency Stop", "vi": "Dừng khẩn cấp" }, { "en": "Start", "vi": "Bắt đầu" }, { "en": "Sleep mode", "vi": "Chế độ ngủ" } ], "correctAnswers": [4], "explanation": { "en": "The controller's LED display shows status like Error, Warning, and E-Stop, but not 'Sleep mode'.", "vi": "Màn hình LED của bộ điều khiển hiển thị các trạng thái như Lỗi, Cảnh báo và Dừng khẩn cấp, nhưng không có 'Chế độ ngủ'." } },
        { "id": "p2q10", "type": "single-select", "question": { "en": "The following description of local/tool coordinates is correct?", "vi": "Mô tả sau đây về tọa độ local/tool là đúng?" }, "options": [ { "en": "World coordinate is not local 0", "vi": "Hệ tọa độ World không phải là local 0" }, { "en": "The Z-axis of tool 1 should align and parallel to the J6 axis.", "vi": "Trục Z của tool 1 phải thẳng hàng và song song với trục J6." }, { "en": "Tool 0 is the center of the J6 mount.", "vi": "Tool 0 là tâm của ngàm J6." }, { "en": "The maximum number of local coordinates is 10.", "vi": "Số lượng hệ tọa độ local tối đa là 10." } ], "correctAnswers": [2], "explanation": { "en": "Tool 0 is the default tool coordinate system, and its origin is located at the center of the mounting face of Joint #6.", "vi": "Tool 0 là hệ tọa độ công cụ mặc định và gốc của nó nằm ở tâm của mặt lắp của Khớp số 6." } },
        { "id": "p2q11", "type": "single-select", "question": { "en": "What environmental status is not appropriate for the EPSON robot controller installation?", "vi": "Tình trạng môi trường nào không phù hợp để lắp đặt bộ điều khiển robot EPSON?" }, "options": [ { "en": "Ambient temperature: 5 to 40 deg.C (with minimal variation)", "vi": "Nhiệt độ môi trường: 5 đến 40 độ C (với sự thay đổi tối thiểu)" }, { "en": "Ambient relative humidity: 20% to 80% (with no condensation)", "vi": "Độ ẩm tương đối môi trường: 20% đến 80% (không ngưng tụ)" }, { "en": "Electrostatic noise: 4KV or higher", "vi": "Nhiễu tĩnh điện: 4KV trở lên" }, { "en": "Base table: Use a base table that is at least 100 mm off the floor.", "vi": "Bàn đế: Sử dụng bàn đế cách sàn ít nhất 100 mm." } ], "correctAnswers": [2], "explanation": { "en": "High electrostatic noise (4KV or higher) can interfere with the controller's electronics and is an inappropriate environment.", "vi": "Nhiễu tĩnh điện cao (4KV trở lên) có thể gây nhiễu cho các thiết bị điện tử của bộ điều khiển và là một môi trường không phù hợp." } },
        { "id": "p2q12", "type": "single-select", "question": { "en": "Which specification of the Power Supply is not correct?", "vi": "Thông số kỹ thuật nào của Nguồn điện không chính xác?" }, "options": [ { "en": "Voltage: 200 VAC to 240 VAC", "vi": "Điện áp: 200 VAC đến 240 VAC" }, { "en": "Phase: three phase", "vi": "Pha: ba pha" }, { "en": "Frequency: 50/60 Hz", "vi": "Tần số: 50/60 Hz" }, { "en": "Momentary Power Interrupt: 10 ms Or less", "vi": "Gián đoạn nguồn tạm thời: 10 ms hoặc ít hơn" }, { "en": "Power consumption: Max. 2.5 KVA", "vi": "Tiêu thụ điện năng: Tối đa 2.5 KVA" }, { "en": "Peak current: Power ON, approx. 150 A (2 ms); Motor ON, approx. 60 A (5 ms).", "vi": "Dòng điện đỉnh: Bật nguồn, xấp xỉ 150 A (2 ms); Bật động cơ, xấp xỉ 60 A (5 ms)." } ], "correctAnswers": [1], "explanation": { "en": "The power supply for the RC180 is single-phase, not three-phase.", "vi": "Nguồn điện cho RC180 là một pha, không phải ba pha." } },
        { "id": "p2q13", "type": "single-select", "question": { "en": "Which description of the operation mode is correct?", "vi": "Mô tả nào về chế độ hoạt động là đúng?" }, "options": [ { "en": "In TEACH mode, the Robot operates in Low power status.", "vi": "Ở chế độ TEACH, Robot hoạt động ở trạng thái công suất thấp." }, { "en": "Auto mode does not include program mode.", "vi": "Chế độ Auto không bao gồm chế độ program." }, { "en": "AUTO mode includes TEACH mode, Program mode, and Auto mode.", "vi": "Chế độ AUTO bao gồm chế độ TEACH, chế độ Program và chế độ Auto." }, { "en": "AUTO mode can not enable automatic operation (program execution).", "vi": "Chế độ AUTO không thể cho phép hoạt động tự động (thực thi chương trình)." } ], "correctAnswers": [0], "explanation": { "en": "TEACH mode is a safety feature that reduces the robot's power and speed to allow for safe manual teaching of points.", "vi": "Chế độ TEACH là một tính năng an toàn giúp giảm công suất và tốc độ của robot để cho phép dạy điểm thủ công một cách an toàn." } },
        { "id": "p2q14", "type": "single-select", "question": { "en": "Which step in the procedure to save the status of the Controller to USB memory is not correct?", "vi": "Bước nào trong quy trình lưu trạng thái của Bộ điều khiển vào bộ nhớ USB không chính xác?" }, "options": [ { "en": "Insert the USB memory into the memory port, then wait approx. 10 seconds for USB memory recognition.", "vi": "Cắm bộ nhớ USB vào cổng bộ nhớ, sau đó đợi khoảng 10 giây để nhận dạng bộ nhớ USB." }, { "en": "Press the trigger button on the Controller.", "vi": "Nhấn nút kích hoạt trên Bộ điều khiển." }, { "en": "When the storage has been completed, -00- is displayed on the seven-segment for two seconds.", "vi": "Khi việc lưu trữ hoàn tất, -00- được hiển thị trên màn hình bảy đoạn trong hai giây." }, { "en": "When the storage has failed, -EE- is displayed on the seven-segment for two seconds.", "vi": "Khi việc lưu trữ không thành công, -EE- được hiển thị trên màn hình bảy đoạn trong hai giây." }, { "en": "When storage is executed during Motor ON status, it won’t cause any problem.", "vi": "Khi việc lưu trữ được thực hiện trong khi động cơ đang BẬT, nó sẽ không gây ra bất kỳ vấn đề nào." } ], "correctAnswers": [4], "explanation": { "en": "Executing storage while the motors are on can cause issues. It should be done with motors off.", "vi": "Thực hiện lưu trữ trong khi động cơ đang bật có thể gây ra sự cố. Nó nên được thực hiện khi động cơ tắt." } },
        { "id": "p2q15", "type": "single-select", "question": { "en": "Which description of the Emergency connector is not correct?", "vi": "Mô tả nào về đầu nối Khẩn cấp không chính xác?" }, "options": [ { "en": "Two Emergency Stop circuits (ESTOP1 and ESTOP2)", "vi": "Hai mạch Dừng khẩn cấp (ESTOP1 và ESTOP2)" }, { "en": "Two Safety Door Latch Release (SDLATCH1 and SDLATCH2)", "vi": "Hai Chốt nhả cửa an toàn (SDLATCH1 và SDLATCH2)" }, { "en": "Four Safety Door Input (SD11, SD12, SD21, SD22)", "vi": "Bốn Đầu vào cửa an toàn (SD11, SD12, SD21, SD22)" }, { "en": "D-sub 30 male pin Mounting style #4 – 40", "vi": "Chân cắm D-sub 30 kiểu lắp #4 – 40" } ], "correctAnswers": [3], "explanation": { "en": "The emergency stop connector is a D-sub 25-pin connector, not 30-pin.", "vi": "Đầu nối dừng khẩn cấp là đầu nối D-sub 25 chân, không phải 30 chân." } },
        { "id": "p2q16", "type": "single-select", "question": { "en": "About robot maintenance, which statement below is not correct?", "vi": "Về bảo trì robot, nhận định nào dưới đây không đúng?" }, "options": [ { "en": "In the controller, the “General” dialog box can display the installation date of the battery and consumption ratio.", "vi": "Trong bộ điều khiển, hộp thoại “General” có thể hiển thị ngày lắp đặt pin và tỷ lệ tiêu thụ." }, { "en": "An alarm occurs when the consumption rate of parts reaches 100%", "vi": "Một báo động xảy ra khi tỷ lệ tiêu thụ của các bộ phận đạt 100%" }, { "en": "“Change Alarm” does not include the purchase or replacement date of the reduction gear unit.", "vi": "“Change Alarm” không bao gồm ngày mua hoặc thay thế của bộ giảm tốc." }, { "en": "The alarm notifying method can be configured by the output bit of the Remote I/O.", "vi": "Phương pháp thông báo báo động có thể được cấu hình bằng bit đầu ra của I/O từ xa." }, { "en": "The alarm cannot be canceled by executing the Reset command or restarting the controller but by the [Maintenance] dialog box.", "vi": "Báo động không thể được hủy bỏ bằng cách thực hiện lệnh Reset hoặc khởi động lại bộ điều khiển mà bằng hộp thoại [Maintenance]." } ], "correctAnswers": [2], "explanation": { "en": "The 'Change Alarm' settings do include maintenance information for the reduction gear units.", "vi": "Cài đặt 'Change Alarm' có bao gồm thông tin bảo trì cho các bộ giảm tốc." } },
        { "id": "p2q17", "type": "single-select", "question": { "en": "About Maintenance Inspection, which statement is not correct?", "vi": "Về Kiểm tra Bảo trì, nhận định nào không đúng?" }, "options": [ { "en": "Inspection points are divided into five stages: daily, monthly, quarterly, biannual and annual.", "vi": "Các điểm kiểm tra được chia thành năm giai đoạn: hàng ngày, hàng tháng, hàng quý, nửa năm và hàng năm." }, { "en": "If the robot system is operated for 250 hours or more per month, inspection points must be added every 250 hours, 750 hours, 1500 hours, and 3000 hours of operation.", "vi": "Nếu hệ thống robot được vận hành từ 250 giờ trở lên mỗi tháng, các điểm kiểm tra phải được thêm vào sau mỗi 250 giờ, 750 giờ, 1500 giờ và 3000 giờ hoạt động." }, { "en": "Clean the fan filter on the side of the controller only performed Quarterly.", "vi": "Vệ sinh bộ lọc quạt bên hông bộ điều khiển chỉ được thực hiện hàng quý." }, { "en": "Battery front side check every 5 years.", "vi": "Kiểm tra mặt trước pin 5 năm một lần." } ], "correctAnswers": [2], "explanation": { "en": "The fan filter should be cleaned monthly, not just quarterly.", "vi": "Bộ lọc quạt nên được vệ sinh hàng tháng, không chỉ hàng quý." } },
        { "id": "p2q18", "type": "single-select", "question": { "en": "Which Option Unit is not listed in the RC180 controller?", "vi": "Đơn vị Tùy chọn nào không được liệt kê trong bộ điều khiển RC180?" }, "options": [ { "en": "Expansion I/O Board", "vi": "Bo mạch I/O mở rộng" }, { "en": "Fieldbus I/O Board", "vi": "Bo mạch I/O Fieldbus" }, { "en": "RS-232C Board", "vi": "Bo mạch RS-232C" }, { "en": "BACnet board", "vi": "Bo mạch BACnet" } ], "correctAnswers": [3], "explanation": { "en": "BACnet is a protocol for building automation and control networks and is not a standard option unit for the RC180 industrial robot controller.", "vi": "BACnet là một giao thức cho các mạng tự động hóa và điều khiển tòa nhà và không phải là một đơn vị tùy chọn tiêu chuẩn cho bộ điều khiển robot công nghiệp RC180." } },
        { "id": "p2q19", "type": "single-select", "question": { "en": "The Fieldbus I/O option can add the Fieldbus slave functions to the robot controller, which one does not include?", "vi": "Tùy chọn Fieldbus I/O có thể thêm các chức năng slave Fieldbus vào bộ điều khiển robot, loại nào không bao gồm?" }, "options": [ { "en": "DeviceNet", "vi": "DeviceNet" }, { "en": "PROFIBUS-DP", "vi": "PROFIBUS-DP" }, { "en": "PROFINET", "vi": "PROFINET" }, { "en": "CC-Link", "vi": "CC-Link" }, { "en": "EtherNet/IP", "vi": "EtherNet/IP" }, { "en": "All the above are included.", "vi": "Tất cả các câu trên đều được bao gồm." } ], "correctAnswers": [5], "explanation": { "en": "The RC180 controller supports all the listed Fieldbus protocols as optional slave functions.", "vi": "Bộ điều khiển RC180 hỗ trợ tất cả các giao thức Fieldbus được liệt kê như các chức năng slave tùy chọn." } },
        { "id": "p2q20", "type": "single-select", "question": { "en": "Please find the description of the Errors code table is not correct in the maintenance chapter.", "vi": "Vui lòng tìm mô tả về bảng mã Lỗi không chính xác trong chương bảo trì." }, "options": [ { "en": "There are 18 types of errors in error codes.", "vi": "Có 18 loại lỗi trong mã lỗi." }, { "en": "Event code: from 1 to 426.", "vi": "Mã sự kiện: từ 1 đến 426." }, { "en": "Warnings code: start from 501.", "vi": "Mã cảnh báo: bắt đầu từ 501." }, { "en": "Controller Main: 1001 ~", "vi": "Bộ điều khiển chính: 1001 ~" }, { "en": "Motor Control: 4001 ~", "vi": "Điều khiển động cơ: 4001 ~" }, { "en": "all above are not correct", "vi": "tất cả các câu trên đều không đúng" } ], "correctAnswers": [1], "explanation": { "en": "The event codes have a specific range, and '1 to 426' is not the correct range described in the documentation.", "vi": "Các mã sự kiện có một phạm vi cụ thể, và '1 đến 426' không phải là phạm vi chính xác được mô tả trong tài liệu." } }
    ],
    "part3": [
        { "id": "p3q1", "type": "single-select", "question": { "en": "In the Function Test of “Do….While” which description below is not correct? `Function Test\nInteger i\ni = 1\nDo While i < 4\n  Print i\n  i = i + 1\nLoop\nFend`", "vi": "Trong Function Test của “Do….While”, mô tả nào dưới đây không đúng? `Function Test\nInteger i\ni = 1\nDo While i < 4\n  Print i\n  i = i + 1\nLoop\nFend`" }, "options": [ { "en": "Add While after Do, and only perform the Do loop when the discriminant is established.", "vi": "Thêm While sau Do, và chỉ thực hiện vòng lặp Do khi điều kiện phân biệt được thiết lập." }, { "en": "Add Until after Do, and stop the Do loop when the discriminant is established.", "vi": "Thêm Until sau Do, và dừng vòng lặp Do khi điều kiện phân biệt được thiết lập." }, { "en": "Terminating the loop when i= 4.", "vi": "Kết thúc vòng lặp khi i= 4." }, { "en": "Debug mode cannot be used to verify the program.", "vi": "Không thể sử dụng chế độ Debug để xác minh chương trình." } ], "correctAnswers": [3], "explanation": { "en": "Debug mode is specifically designed to help verify and step through programs like this.", "vi": "Chế độ Debug được thiết kế đặc biệt để giúp xác minh và chạy từng bước các chương trình như thế này." } },
        { "id": "p3q2", "type": "single-select", "question": { "en": "What description is not correct regarding the following code? `... Do While i < 4\nGo P(i) +Z(50)\nGo P(i)\nGo P(i) +Z(50)\ni = i + 1\nLoop ...`", "vi": "Mô tả nào không đúng về đoạn mã sau? `... Do While i < 4\nGo P(i) +Z(50)\nGo P(i)\nGo P(i) +Z(50)\ni = i + 1\nLoop ...`" }, "options": [ { "en": "If we remove i = i + 1, it becomes an infinite loop.", "vi": "Nếu chúng ta xóa i = i + 1, nó sẽ trở thành một vòng lặp vô hạn." }, { "en": "The robot arm goes P1, P2, P3, and Home in sequence four times.", "vi": "Cánh tay robot đi đến P1, P2, P3 và Home theo trình tự bốn lần." }, { "en": "Stop at Home in the end.", "vi": "Dừng ở Home cuối cùng." }, { "en": "Z(50) means Z axis = 50 mm.", "vi": "Z(50) có nghĩa là trục Z = 50 mm." } ], "correctAnswers": [3], "explanation": { "en": "'+Z(50)' is a relative movement, meaning it moves 50mm up from the point's Z coordinate, it does not mean Z=50.", "vi": "'+Z(50)' là một chuyển động tương đối, có nghĩa là nó di chuyển lên 50mm từ tọa độ Z của điểm, nó không có nghĩa là Z=50." } },
        { "id": "p3q3", "type": "single-select", "question": { "en": "In the following code, which description is not correct? `... If feed5Ready = On Then\nCall PP\nElse ...`", "vi": "Trong đoạn mã sau, mô tả nào không đúng? `... If feed5Ready = On Then\nCall PP\nElse ...`" }, "options": [ { "en": "When Sw(5) = 0, enter “Else” and print \"Input No. 5 switch is not ON\" and \"Press Start\".", "vi": "Khi Sw(5) = 0, vào “Else” và in \"Input No. 5 switch is not ON\" và \"Press Start\"." }, { "en": "When Sw(5) = 1, enter “Then” and print \"Input No. 5 switch is ON\", and then activate Output 5.", "vi": "Khi Sw(5) = 1, vào “Then” và in \"Input No. 5 switch is ON\", sau đó kích hoạt Output 5." }, { "en": "The name of the calle Function is PP.", "vi": "Tên của Hàm được gọi là PP." }, { "en": "Pressed No. 5 button to enter the called Function during debugging.", "vi": "Nhấn nút số 5 để vào Hàm được gọi trong khi gỡ lỗi." } ], "correctAnswers": [3], "explanation": { "en": "The code checks the state of input Sw(5), it is not waiting for a button press during debug. The state must be set for the condition to be met.", "vi": "Mã kiểm tra trạng thái của đầu vào Sw(5), nó không chờ một nút nhấn trong quá trình gỡ lỗi. Trạng thái phải được đặt để điều kiện được đáp ứng." } },
        { "id": "p3q4", "type": "single-select", "question": { "en": "Which statement (or claim) about “Time” is not correct?", "vi": "Phát biểu (hoặc tuyên bố) nào về “Time” không chính xác?" }, "options": [ { "en": "Time$, covert number to text format.", "vi": "Time$, chuyển đổi số sang định dạng văn bản." }, { "en": "Integer hr, hr = Time(0), set time unit = hour.", "vi": "Integer hr, hr = Time(0), đặt đơn vị thời gian = giờ." }, { "en": "Integer min, min = Time(1), set time unit = minute.", "vi": "Integer min, min = Time(1), đặt đơn vị thời gian = phút." }, { "en": "Integer sec, sec = Time(2), set time unit = sec.", "vi": "Integer sec, sec = Time(2), đặt đơn vị thời gian = giây." } ], "correctAnswers": [3], "explanation": { "en": "Time(2) returns the current second. `Integer sec, sec = Time(2)` correctly assigns the current second to the variable 'sec'. The statement itself is correct, but there might be a misunderstanding in the question's premise.", "vi": "Time(2) trả về giây hiện tại. `Integer sec, sec = Time(2)` gán chính xác giây hiện tại cho biến 'sec'. Bản thân câu lệnh là đúng, nhưng có thể có sự hiểu lầm trong tiền đề của câu hỏi." } },
        { "id": "p3q5", "type": "single-select", "question": { "en": "In the Pallet command - Pallet palletNumber, Pi, Pj, Pk [,Pm ], columns, rows.; what statement is not correct?", "vi": "Trong lệnh Pallet - Pallet palletNumber, Pi, Pj, Pk [,Pm ], columns, rows.; phát biểu nào không đúng?" }, "options": [ { "en": "palletNumber Pallet number represented by an integer number from 0 to 15", "vi": "palletNumber Số pallet được biểu thị bằng một số nguyên từ 0 đến 15" }, { "en": "Pi, Pj, Pk Point variables which define standard 3-point pallet position", "vi": "Pi, Pj, Pk Các biến điểm xác định vị trí pallet 3 điểm tiêu chuẩn" }, { "en": "Pm Optional. Point variable which is used with Pi, Pj, and Pk to define 3 point pallet.", "vi": "Pm Tùy chọn. Biến điểm được sử dụng với Pi, Pj và Pk để xác định pallet 3 điểm." }, { "en": "columns Integer expression representing the number of points on the Pi-to-Pj side of the pallet. The range is from 1 to 32767.", "vi": "columns Biểu thức nguyên biểu thị số điểm ở phía Pi-đến-Pj của pallet. Phạm vi từ 1 đến 32767." }, { "en": "rows Integer expression representing the number of points on the Pi-to-Pk side of the pallet. The range is from 1 to 32767.", "vi": "rows Biểu thức nguyên biểu thị số điểm ở phía Pi-đến-Pk của pallet. Phạm vi từ 1 đến 32767." } ], "correctAnswers": [2], "explanation": { "en": "Pm is an optional point variable used to define a 4-point pallet, not a 3-point pallet.", "vi": "Pm là một biến điểm tùy chọn được sử dụng để xác định pallet 4 điểm, không phải pallet 3 điểm." } },
        { "id": "p3q6", "type": "single-select", "question": { "en": "Which description of EPSON RC+5.0 features is not correct?", "vi": "Mô tả nào về các tính năng của EPSON RC+5.0 không chính xác?" }, "options": [ { "en": "Runs on Microsoft Windows XP, Windows Vista, and Windows 7, but not Windows 10.", "vi": "Chạy trên Microsoft Windows XP, Windows Vista và Windows 7, nhưng không chạy trên Windows 10." }, { "en": "One PC can be used to manage several controllers.", "vi": "Một PC có thể được sử dụng để quản lý một số bộ điều khiển." }, { "en": "SPEL+ programming language. A powerful, easy-to-use BASIC-like programming language that supports multi-tasking, robot motion control, I/O control, and networking.", "vi": "Ngôn ngữ lập trình SPEL+. Một ngôn ngữ lập trình mạnh mẽ, dễ sử dụng giống như BASIC hỗ trợ đa nhiệm, điều khiển chuyển động robot, điều khiển I/O và mạng." }, { "en": "Have “Wizards” for robot tools, local coordinate systems, robot calibration", "vi": "Có “Wizards” cho các công cụ robot, hệ tọa độ cục bộ, hiệu chuẩn robot" } ], "correctAnswers": [0], "explanation": { "en": "EPSON RC+ software versions (like 7.0 and later) are compatible with Windows 10.", "vi": "Các phiên bản phần mềm EPSON RC+ (như 7.0 trở lên) tương thích với Windows 10." } },
        { "id": "p3q7", "type": "single-select", "question": { "en": "What statement is not true about “Commands” and “Statements” in SPEL+ language?", "vi": "Phát biểu nào không đúng về “Lệnh” và “Câu lệnh” trong ngôn ngữ SPEL+?" }, "options": [ { "en": "A command is executed immediately.", "vi": "Một lệnh được thực thi ngay lập tức." }, { "en": "Statements can be used only in programs.", "vi": "Câu lệnh chỉ có thể được sử dụng trong các chương trình." }, { "en": "Statements can include more than one SPEL+ instruction by using a semi-colon (;) to separate instructions.", "vi": "Câu lệnh có thể bao gồm nhiều hơn một chỉ thị SPEL+ bằng cách sử dụng dấu chấm phẩy (;) để phân tách các chỉ thị." }, { "en": "The maximum length for a statement is 20 characters.", "vi": "Độ dài tối đa cho một câu lệnh là 20 ký tự." } ], "correctAnswers": [3], "explanation": { "en": "The maximum length for a statement in SPEL+ is 255 characters, not 20.", "vi": "Độ dài tối đa cho một câu lệnh trong SPEL+ là 255 ký tự, không phải 20." } },
        { "id": "p3q8", "type": "single-select", "question": { "en": "Which naming restriction about Function and variable names is not true?", "vi": "Hạn chế đặt tên nào về tên Hàm và biến không đúng?" }, "options": [ { "en": "Function and variable names can include up to 32 alphanumeric characters and the underscore character.", "vi": "Tên hàm và biến có thể bao gồm tối đa 32 ký tự chữ và số và ký tự gạch dưới." }, { "en": "Characters can be upper case or lower case.", "vi": "Các ký tự có thể là chữ hoa hoặc chữ thường." }, { "en": "Function and variable names can begin with a numeric digit or underscore.", "vi": "Tên hàm và biến có thể bắt đầu bằng một chữ số hoặc dấu gạch dưới." }, { "en": "The strings that are already used as keywords cannot be used. (Example: Go / On)", "vi": "Các chuỗi đã được sử dụng làm từ khóa không thể được sử dụng. (Ví dụ: Go / On)" } ], "correctAnswers": [2], "explanation": { "en": "Function and variable names must begin with an alphabetic character, not a number or underscore.", "vi": "Tên hàm và biến phải bắt đầu bằng một ký tự chữ cái, không phải số hoặc dấu gạch dưới." } },
        { "id": "p3q9", "type": "single-select", "question": { "en": "About the “String” description, which one is not correct?", "vi": "Về mô tả “Chuỗi”, cái nào không đúng?" }, "options": [ { "en": "The strings that are already used as keywords cannot be used. (Example: Go / On)", "vi": "Các chuỗi đã được sử dụng làm từ khóa không thể được sử dụng. (Ví dụ: Go / On)" }, { "en": "String variables must have an additional dollar sign ('$') suffix.", "vi": "Các biến chuỗi phải có một hậu tố đô la ('$') bổ sung." }, { "en": "String size is 4 bytes.", "vi": "Kích thước chuỗi là 4 byte." }, { "en": "String variables should be placed in the front of the sketch.", "vi": "Các biến chuỗi nên được đặt ở phía trước của bản phác thảo." } ], "correctAnswers": [2], "explanation": { "en": "The size of a string is not fixed at 4 bytes; it depends on the number of characters it contains.", "vi": "Kích thước của một chuỗi không cố định ở 4 byte; nó phụ thuộc vào số lượng ký tự mà nó chứa." } },
        { "id": "p3q10", "type": "single-select", "question": { "en": "Which description of operators for the SPEL+ language is not correct?", "vi": "Mô tả nào về các toán tử cho ngôn ngữ SPEL+ không đúng?" }, "options": [ { "en": "And - Performs logical and bitwise AND operation", "vi": "And - Thực hiện phép toán AND logic và bit" }, { "en": "Xor - Performs the bitwise Xor operation on the values of the operands.", "vi": "Xor - Thực hiện phép toán Xor bit trên các giá trị của các toán hạng." }, { "en": "Mod - Returns the remainder obtained by dividing a numeric expression by another numeric expression.", "vi": "Mod - Trả về phần dư thu được bằng cách chia một biểu thức số cho một biểu thức số khác." }, { "en": "** - Exponentiation", "vi": "** - Lũy thừa" }, { "en": "All the above are correct.", "vi": "Tất cả các câu trên đều đúng." } ], "correctAnswers": [4], "explanation": { "en": "All the listed operators (And, Xor, Mod, **) are correctly described for the SPEL+ language.", "vi": "Tất cả các toán tử được liệt kê (And, Xor, Mod, **) được mô tả chính xác cho ngôn ngữ SPEL+." } },
        { "id": "p3q11", "type": "single-select", "question": { "en": "There are three different scopes for variables in SPEL+, which one below is not included?", "vi": "Có ba phạm vi khác nhau cho các biến trong SPEL+, cái nào dưới đây không được bao gồm?" }, "options": [ { "en": "Local variables", "vi": "Biến cục bộ" }, { "en": "Module variables", "vi": "Biến mô-đun" }, { "en": "Global variables", "vi": "Biến toàn cục" }, { "en": "Special variables", "vi": "Biến đặc biệt" } ], "correctAnswers": [3], "explanation": { "en": "The three variable scopes in SPEL+ are Local, Module, and Global. 'Special variables' is not a defined scope.", "vi": "Ba phạm vi biến trong SPEL+ là Cục bộ, Mô-đun và Toàn cục. 'Biến đặc biệt' không phải là một phạm vi được xác định." } },
        { "id": "p3q12", "type": "single-select", "question": { "en": "What description of Global variables below is not correct?", "vi": "Mô tả nào về biến Toàn cục dưới đây không đúng?" }, "options": [ { "en": "Global variables can be shared between all functions in a project.", "vi": "Các biến toàn cục có thể được chia sẻ giữa tất cả các hàm trong một dự án." }, { "en": "To declare global variables at the beginning of the program before any Function statements.", "vi": "Để khai báo các biến toàn cục ở đầu chương trình trước bất kỳ câu lệnh Hàm nào." }, { "en": "One way to indicate that variables are global is to precede the name with \"g_\".", "vi": "Một cách để chỉ ra rằng các biến là toàn cục là đặt trước tên bằng \"g_\"." }, { "en": "Preserved variables are stored in the remote computer.", "vi": "Các biến được bảo toàn được lưu trữ trong máy tính từ xa." } ], "correctAnswers": [3], "explanation": { "en": "Global preserved variables are stored in the controller's memory, not a remote computer, so they retain their values even when the controller is turned off.", "vi": "Các biến toàn cục được bảo toàn được lưu trữ trong bộ nhớ của bộ điều khiển, không phải là máy tính từ xa, vì vậy chúng giữ lại giá trị của mình ngay cả khi bộ điều khiển bị tắt." } },
        { "id": "p3q13", "type": "single-select", "question": { "en": "Which description of string commands available in SPEL+ is not correct?", "vi": "Mô tả nào về các lệnh chuỗi có sẵn trong SPEL+ không đúng?" }, "options": [ { "en": "Asc: Returns the decimal ASCII value of the first character in a string.", "vi": "Asc: Trả về giá trị ASCII thập phân của ký tự đầu tiên trong một chuỗi." }, { "en": "Chr$: Converts a one character string into an ASCII value.", "vi": "Chr$: Chuyển đổi một chuỗi một ký tự thành một giá trị ASCII." }, { "en": "InStr: Returns the position of a substring within a string.", "vi": "InStr: Trả về vị trí của một chuỗi con trong một chuỗi." }, { "en": "Len: Returns the length (number of characters) of a string.", "vi": "Len: Trả về độ dài (số ký tự) của một chuỗi." } ], "correctAnswers": [1], "explanation": { "en": "Chr$ does the opposite: it converts a numeric ASCII value into a one-character string.", "vi": "Chr$ làm điều ngược lại: nó chuyển đổi một giá trị ASCII số thành một chuỗi một ký tự." } },
        { "id": "p3q14", "type": "single-select", "question": { "en": "Which statement about Labels is correct?", "vi": "Phát biểu nào về Nhãn là đúng?" }, "options": [ { "en": "A program label is an alphanumeric name followed by a colon (\":\")", "vi": "Một nhãn chương trình là một tên chữ và số theo sau là dấu hai chấm (\":\")" }, { "en": "Label used to mark a location in a program for a GoTo or GoSub statement. (example: MainAbort: )", "vi": "Nhãn được sử dụng để đánh dấu một vị trí trong một chương trình cho một câu lệnh GoTo hoặc GoSub. (ví dụ: MainAbort: )" }, { "en": "The name may be up to 32 characters long.", "vi": "Tên có thể dài tối đa 32 ký tự." }, { "en": "You cannot use any SPEL+ keywords as labels.", "vi": "Bạn không thể sử dụng bất kỳ từ khóa SPEL+ nào làm nhãn." }, { "en": "All the above are correct.", "vi": "Tất cả các câu trên đều đúng." } ], "correctAnswers": [4], "explanation": { "en": "All the given statements about labels in SPEL+ are correct.", "vi": "Tất cả các phát biểu đã cho về nhãn trong SPEL+ đều đúng." } },
        { "id": "p3q15", "type": "single-select", "question": { "en": "What statement about Error handling is not correct?", "vi": "Phát biểu nào về xử lý Lỗi không đúng?" }, "options": [ { "en": "OnErr: Use the OnErr statement to define the location of the error handling routine.", "vi": "OnErr: Sử dụng câu lệnh OnErr để xác định vị trí của quy trình xử lý lỗi." }, { "en": "Error: Generate a user defined error which can be caught by an error handler.", "vi": "Error: Tạo ra một lỗi do người dùng xác định có thể được bắt bởi một trình xử lý lỗi." }, { "en": "Err: Generate a user defined error which can be caught by an error handler.", "vi": "Err: Tạo ra một lỗi do người dùng xác định có thể được bắt bởi một trình xử lý lỗi." }, { "en": "ErrMsg$: Use ErrMsg$ to retrieve the error message associated with a specified error number.", "vi": "ErrMsg$: Sử dụng ErrMsg$ để truy xuất thông báo lỗi được liên kết với một số lỗi được chỉ định." } ], "correctAnswers": [2], "explanation": { "en": "'Err' is a function that returns the current error number. The 'Error' statement is used to generate a user-defined error.", "vi": "'Err' là một hàm trả về số lỗi hiện tại. Câu lệnh 'Error' được sử dụng để tạo ra một lỗi do người dùng xác định." } },
        { "id": "p3q16", "type": "single-select", "question": { "en": "What description of Multi-tasking is not correct?", "vi": "Mô tả nào về Đa nhiệm không đúng?" }, "options": [ { "en": "SPEL+ supports up to 16 tasks running simultaneously.", "vi": "SPEL+ hỗ trợ tối đa 16 tác vụ chạy đồng thời." }, { "en": "Use the Xqt statement to start another task from within a function.", "vi": "Sử dụng câu lệnh Xqt để bắt đầu một tác vụ khác từ bên trong một hàm." }, { "en": "“Resume” is not the Statement in Multi-tasking.", "vi": "“Resume” không phải là Câu lệnh trong Đa nhiệm." }, { "en": "Xqt Conveyor means “Start the conveyor task”.", "vi": "Xqt Conveyor có nghĩa là “Bắt đầu tác vụ băng chuyền”." } ], "correctAnswers": [2], "explanation": { "en": "'Resume' is a valid statement used to continue a task that was paused with the 'Pause' statement.", "vi": "'Resume' là một câu lệnh hợp lệ được sử dụng để tiếp tục một tác vụ đã bị tạm dừng bằng câu lệnh 'Pause'." } },
        { "id": "p3q17", "type": "single-select", "question": { "en": "Which one coordinate system is not included in the EPSON robot coordinate system?", "vi": "Hệ tọa độ nào không được bao gồm trong hệ tọa độ robot EPSON?" }, "options": [ { "en": "Robot Coordinate System", "vi": "Hệ tọa độ Robot" }, { "en": "Local Coordinate System", "vi": "Hệ tọa độ Cục bộ" }, { "en": "Tool Coordinate System", "vi": "Hệ tọa độ Công cụ" }, { "en": "World Coordinate System", "vi": "Hệ tọa độ Thế giới" } ], "correctAnswers": [3], "explanation": { "en": "The EPSON system uses Robot, Local, and Tool coordinate systems. The 'World' coordinate system is often referred to as 'Local 0' or the Base coordinate system within the EPSON environment.", "vi": "Hệ thống EPSON sử dụng các hệ tọa độ Robot, Cục bộ và Công cụ. Hệ tọa độ 'Thế giới' thường được gọi là 'Cục bộ 0' hoặc hệ tọa độ Cơ sở trong môi trường EPSON." } },
        { "id": "p3q18", "type": "single-select", "question": { "en": "Regarding Tool Coordinate Systems, which statement in the following is not correct?", "vi": "Về Hệ tọa độ Công cụ, phát biểu nào sau đây không đúng?" }, "options": [ { "en": "TOOL 0 of a 6-axis robot is the flange side center of the sixth joint.", "vi": "TOOL 0 của một robot 6 trục là tâm mặt bích của khớp thứ sáu." }, { "en": "The position is specified by the position data (X, Y, Z).", "vi": "Vị trí được xác định bởi dữ liệu vị trí (X, Y, Z)." }, { "en": "The orientation is specified by the orientation data (U, V, W).", "vi": "Hướng được xác định bởi dữ liệu hướng (U, V, W)." }, { "en": "The default TOOL 0 coordinate systems are defined by the user.", "vi": "Các hệ tọa độ TOOL 0 mặc định được xác định bởi người dùng." } ], "correctAnswers": [3], "explanation": { "en": "The default TOOL 0 coordinate system is predefined by the system manufacturer (EPSON) and cannot be changed by the user.", "vi": "Hệ tọa độ TOOL 0 mặc định được xác định trước bởi nhà sản xuất hệ thống (EPSON) và không thể thay đổi bởi người dùng." } },
        { "id": "p3q19", "type": "single-select", "question": { "en": "What description of ECP (external control point) is not correct?", "vi": "Mô tả nào về ECP (điểm điều khiển bên ngoài) không đúng?" }, "options": [ { "en": "An ECP motion is when the robot arm holding a part follows a specified trajectory (part’s edges, etc.) using an outside fixed tool.", "vi": "Một chuyển động ECP là khi cánh tay robot giữ một bộ phận đi theo một quỹ đạo được chỉ định (cạnh của bộ phận, v.v.) bằng cách sử dụng một công cụ cố định bên ngoài." }, { "en": "ECP definition by ECPSet statement and selection by ECP statement.", "vi": "Định nghĩa ECP bằng câu lệnh ECPSet và lựa chọn bằng câu lệnh ECP." }, { "en": "ECP motion commands cannot execute additional functions of Move, Arc3, Curve, and CVMove commands.", "vi": "Các lệnh chuyển động ECP không thể thực hiện các chức năng bổ sung của các lệnh Move, Arc3, Curve và CVMove." }, { "en": "Up to 15 ECP coordinate systems can be defined.", "vi": "Có thể xác định tối đa 15 hệ tọa độ ECP." } ], "correctAnswers": [2], "explanation": { "en": "ECP motion commands can indeed be used with commands like Move, Arc, etc., to control the external point along a path.", "vi": "Các lệnh chuyển động ECP thực sự có thể được sử dụng với các lệnh như Move, Arc, v.v., để điều khiển điểm bên ngoài dọc theo một đường đi." } },
        { "id": "p3q20", "type": "single-select", "question": { "en": "Which type of I/O is not included in the RC180 controller I/O?", "vi": "Loại I/O nào không được bao gồm trong I/O của bộ điều khiển RC180?" }, "options": [ { "en": "Standard I/O", "vi": "I/O tiêu chuẩn" }, { "en": "Expansion I/O", "vi": "I/O mở rộng" }, { "en": "Fieldbus I/O", "vi": "I/O Fieldbus" }, { "en": "Memory I/O", "vi": "I/O bộ nhớ" }, { "en": "Virtual I/O", "vi": "I/O ảo" } ], "correctAnswers": [4], "explanation": { "en": "'Virtual I/O' is not a standard type. The RC180 has Standard, Expansion, Fieldbus, and Memory I/O.", "vi": "'I/O ảo' không phải là một loại tiêu chuẩn. RC180 có I/O Tiêu chuẩn, Mở rộng, Fieldbus và Bộ nhớ." } }
    ],
    "part4": [
        { "id": "p4q1", "type": "single-select", "section": { "en": "Program Modes", "vi": "Chế độ chương trình" }, "question": { "en": "Which mode enables point data teaching and checking close to the Robot using the Teach Pendant?", "vi": "Chế độ nào cho phép dạy điểm dữ liệu và kiểm tra gần Robot bằng Tay cầm điều khiển?" }, "options": [ { "en": "AUTO mode", "vi": "Chế độ AUTO" }, { "en": "Program mode", "vi": "Chế độ Program" }, { "en": "TEACH mode", "vi": "Chế độ TEACH" }, { "en": "None of the above", "vi": "Không có câu nào đúng" } ], "correctAnswers": [2], "explanation": { "en": "TEACH mode is specifically designed for safely teaching and checking points with reduced robot power.", "vi": "Chế độ TEACH được thiết kế đặc biệt để dạy và kiểm tra điểm một cách an toàn với công suất robot giảm." } },
        { "id": "p4q2", "type": "single-select", "section": { "en": "Program Modes", "vi": "Chế độ chương trình" }, "question": { "en": "Which mode enables the automatic operation (program execution) of the Robot system for the manufacturing operation?", "vi": "Chế độ nào cho phép vận hành tự động (thực thi chương trình) của hệ thống Robot cho hoạt động sản xuất?" }, "options": [ { "en": "AUTO mode", "vi": "Chế độ AUTO" }, { "en": "Program mode", "vi": "Chế độ Program" }, { "en": "TEACH mode", "vi": "Chế độ TEACH" }, { "en": "None of the above", "vi": "Không có câu nào đúng" } ], "correctAnswers": [0], "explanation": { "en": "AUTO mode is used for running programs in a production environment.", "vi": "Chế độ AUTO được sử dụng để chạy các chương trình trong môi trường sản xuất." } },
        { "id": "p4q3", "type": "single-select", "section": { "en": "Program Modes", "vi": "Chế độ chương trình" }, "question": { "en": "Which mode cannot operate the Robots or run programs with the Safety Door open?", "vi": "Chế độ nào không thể vận hành Robot hoặc chạy chương trình khi Cửa an toàn đang mở?" }, "options": [ { "en": "AUTO mode", "vi": "Chế độ AUTO" }, { "en": "Program mode", "vi": "Chế độ Program" }, { "en": "TEACH mode", "vi": "Chế độ TEACH" }, { "en": "None of the above", "vi": "Không có câu nào đúng" } ], "correctAnswers": [0], "explanation": { "en": "For safety, AUTO mode requires the safety door to be closed to operate at full speed and power.", "vi": "Vì lý do an toàn, chế độ AUTO yêu cầu cửa an toàn phải được đóng để hoạt động ở tốc độ và công suất tối đa." } },
        { "id": "p4q4", "type": "single-select", "section": { "en": "Program Modes", "vi": "Chế độ chương trình" }, "question": { "en": "How can you switch to TEACH mode?", "vi": "Làm cách nào để chuyển sang chế độ TEACH?" }, "options": [ { "en": "Turn the mode selector key switch to \"Auto\" and turn on the latch release input signal", "vi": "Xoay công tắc chọn chế độ sang \"Auto\" và bật tín hiệu đầu vào nhả chốt" }, { "en": "Turn the mode selector key switch to \"Program\"", "vi": "Xoay công tắc chọn chế độ sang \"Program\"" }, { "en": "Turn the mode selector key switch to \"Teach\"", "vi": "Xoay công tắc chọn chế độ sang \"Teach\"" }, { "en": "None of the above", "vi": "Không có câu nào đúng" } ], "correctAnswers": [2], "explanation": { "en": "TEACH mode is selected using the physical key switch on the controller.", "vi": "Chế độ TEACH được chọn bằng công tắc khóa vật lý trên bộ điều khiển." } },
        { "id": "p4q5", "type": "single-select", "section": { "en": "Program Modes", "vi": "Chế độ chương trình" }, "question": { "en": "What is the Program mode used for?", "vi": "Chế độ Program được sử dụng để làm gì?" }, "options": [ { "en": "Point data teaching", "vi": "Dạy dữ liệu điểm" }, { "en": "Programming, debug, adjust", "vi": "Lập trình, gỡ lỗi, điều chỉnh" }, { "en": "Automatic operation", "vi": "Vận hành tự động" }, { "en": "Checking close to the Robot", "vi": "Kiểm tra gần Robot" } ], "correctAnswers": [1], "explanation": { "en": "Program mode allows for development tasks like writing code, debugging, and adjusting the system, separate from live automatic operation.", "vi": "Chế độ Program cho phép các tác vụ phát triển như viết mã, gỡ lỗi và điều chỉnh hệ thống, tách biệt với hoạt động tự động trực tiếp." } },
        { "id": "p4q6", "type": "single-select", "section": { "en": "Safety", "vi": "An toàn" }, "question": { "en": "What is the purpose of the Safety Door switch?", "vi": "Mục đích của công tắc Cửa an toàn là gì?" }, "options": [ { "en": "To open the Safety Door", "vi": "Để mở Cửa an toàn" }, { "en": "To activate safety features", "vi": "Để kích hoạt các tính năng an toàn" }, { "en": "To hold up the program temporarily", "vi": "Để tạm dừng chương trình" }, { "en": "To connect the Safety Door to the EMERGENCY connector", "vi": "Để kết nối Cửa an toàn với đầu nối KHẨN CẤP" } ], "correctAnswers": [1], "explanation": { "en": "The safety door switch is a key part of the safety circuit, designed to stop or limit robot operation when the door is open.", "vi": "Công tắc cửa an toàn là một phần quan trọng của mạch an toàn, được thiết kế để dừng hoặc giới hạn hoạt động của robot khi cửa mở." } },
        { "id": "p4q7", "type": "single-select", "section": { "en": "Safety", "vi": "An toàn" }, "question": { "en": "What happens when the Safety Door is opened?", "vi": "Điều gì xảy ra khi Cửa an toàn được mở?" }, "options": [ { "en": "Activation of the interlock switch", "vi": "Kích hoạt công tắc khóa liên động" }, { "en": "Activation of the EMERGENCY connector", "vi": "Kích hoạt đầu nối KHẨN CẤP" }, { "en": "Permanent shutdown of the program", "vi": "Tắt vĩnh viễn chương trình" }, { "en": "Temporary hold-up of the program", "vi": "Tạm dừng chương trình" } ], "correctAnswers": [3], "explanation": { "en": "Opening the safety door triggers an interlock that typically puts the program and robot motion on hold for safety.", "vi": "Mở cửa an toàn sẽ kích hoạt một khóa liên động thường tạm dừng chương trình và chuyển động của robot để đảm bảo an toàn." } },
        { "id": "p4q8", "type": "single-select", "section": { "en": "Safety", "vi": "An toàn" }, "question": { "en": "Which mode cannot operate the Robots or run programs with the Safety Door open?", "vi": "Chế độ nào không thể vận hành Robot hoặc chạy chương trình khi Cửa an toàn đang mở?" }, "options": [ { "en": "AUTO mode", "vi": "Chế độ AUTO" }, { "en": "Program mode", "vi": "Chế độ Program" }, { "en": "TEACH mode", "vi": "Chế độ TEACH" }, { "en": "None of the above", "vi": "Không có câu nào đúng" } ], "correctAnswers": [0], "explanation": { "en": "AUTO mode requires all safety measures, including the door being closed, to be active for full operation.", "vi": "Chế độ AUTO yêu cầu tất cả các biện pháp an toàn, bao gồm cả việc đóng cửa, phải được kích hoạt để hoạt động đầy đủ." } },
        { "id": "p4q9", "type": "single-select", "section": { "en": "Safety", "vi": "An toàn" }, "question": { "en": "What is the interlock of the Safety Door called?", "vi": "Khóa liên động của Cửa an toàn được gọi là gì?" }, "options": [ { "en": "EMERGENCY switch", "vi": "Công tắc KHẨN CẤP" }, { "en": "Working zone switch", "vi": "Công tắc vùng làm việc" }, { "en": "Safety Door switch", "vi": "Công tắc Cửa an toàn" }, { "en": "Manipulator switch", "vi": "Công tắc tay máy" } ], "correctAnswers": [2], "explanation": { "en": "The switch that detects if the safety door is open or closed is called the Safety Door switch.", "vi": "Công tắc phát hiện cửa an toàn đang mở hay đóng được gọi là công tắc Cửa an toàn." } },
        { "id": "p4q10", "type": "single-select", "section": { "en": "Backup & Restore", "vi": "Sao lưu & Phục hồi" }, "question": { "en": "What is the purpose of the \"Backup Controller\" function in EPSON RC+ 5.0?", "vi": "Mục đích của chức năng \"Backup Controller\" trong EPSON RC+ 5.0 là gì?" }, "options": [ { "en": "To create a copy of the robot program", "vi": "Để tạo một bản sao của chương trình robot" }, { "en": "To save the Controller setup data for future use", "vi": "Để lưu dữ liệu cài đặt của Bộ điều khiển để sử dụng trong tương lai" }, { "en": "To reset the robot to its default settings", "vi": "Để đặt lại robot về cài đặt mặc định" }, { "en": "To transfer project files to the Controller", "vi": "Để chuyển các tệp dự án sang Bộ điều khiển" } ], "correctAnswers": [1], "explanation": { "en": "The backup function saves all critical controller data, including configuration, calibration, and programs.", "vi": "Chức năng sao lưu lưu tất cả dữ liệu quan trọng của bộ điều khiển, bao gồm cấu hình, hiệu chuẩn và chương trình." } },
        { "id": "p4q11", "type": "single-select", "section": { "en": "Backup & Restore", "vi": "Sao lưu & Phục hồi" }, "question": { "en": "When should you execute the \"Backup Controller\" function?", "vi": "Khi nào bạn nên thực hiện chức năng \"Backup Controller\"?" }, "options": [ { "en": "After maintenance has been performed", "vi": "Sau khi đã thực hiện bảo trì" }, { "en": "Before changing the robot program", "vi": "Trước khi thay đổi chương trình robot" }, { "en": "Only when there are configuration mistakes", "vi": "Chỉ khi có lỗi cấu hình" }, { "en": "Once a week", "vi": "Mỗi tuần một lần" } ], "correctAnswers": [1], "explanation": { "en": "It is best practice to back up the controller before making any changes to the program or configuration.", "vi": "Tốt nhất là sao lưu bộ điều khiển trước khi thực hiện bất kỳ thay đổi nào đối với chương trình hoặc cấu hình." } },
        { "id": "p4q12", "type": "single-select", "section": { "en": "Backup & Restore", "vi": "Sao lưu & Phục hồi" }, "question": { "en": "Which file contains the initial configuration for various Controller parameters?", "vi": "Tệp nào chứa cấu hình ban đầu cho các thông số khác nhau của Bộ điều khiển?" }, "options": [ { "en": "Backup.txt", "vi": "Backup.txt" }, { "en": "InitFileSrc.txt", "vi": "InitFileSrc.txt" }, { "en": "GlobalPreserves.dat", "vi": "GlobalPreserves.dat" }, { "en": "CurrentMnp01.PRMr", "vi": "CurrentMnp01.PRMr" } ], "correctAnswers": [1], "explanation": { "en": "InitFileSrc.txt holds the initial source configuration for controller parameters.", "vi": "InitFileSrc.txt chứa cấu hình nguồn ban đầu cho các thông số của bộ điều khiển." } },
        { "id": "p4q13", "type": "single-select", "section": { "en": "Maintenance", "vi": "Bảo trì" }, "question": { "en": "What is the consequence if the batteries (lithium batteries) for the controller and manipulator are completely drained?", "vi": "Hậu quả là gì nếu pin (pin lithium) cho bộ điều khiển và tay máy bị cạn kiệt hoàn toàn?" }, "options": [ { "en": "The robot parameters will be recalibrated automatically.", "vi": "Các thông số robot sẽ được hiệu chỉnh lại tự động." }, { "en": "The robot will go into a sleep mode.", "vi": "Robot sẽ chuyển sang chế độ ngủ." }, { "en": "Robot parameters will be lost, requiring recalibration.", "vi": "Các thông số robot sẽ bị mất, cần phải hiệu chỉnh lại." }, { "en": "The robot will continue functioning normally.", "vi": "Robot sẽ tiếp tục hoạt động bình thường." } ], "correctAnswers": [2], "explanation": { "en": "The batteries maintain the encoder positions and other parameters. If they are drained, this data is lost, and the robot must be recalibrated.", "vi": "Pin duy trì vị trí bộ mã hóa và các thông số khác. Nếu chúng bị cạn kiệt, dữ liệu này sẽ bị mất và robot phải được hiệu chỉnh lại." } },
        { "id": "p4q14", "type": "single-select", "section": { "en": "Maintenance", "vi": "Bảo trì" }, "question": { "en": "How is the recommended replacement time for the battery calculated?", "vi": "Thời gian thay thế pin được khuyến nghị được tính như thế nào?" }, "options": [ { "en": "Based on the robot's weight", "vi": "Dựa trên trọng lượng của robot" }, { "en": "Based on the robot's height", "vi": "Dựa trên chiều cao của robot" }, { "en": "Based on the battery's voltage", "vi": "Dựa trên điện áp của pin" }, { "en": "Based on the battery's capacity", "vi": "Dựa trên dung lượng của pin" } ], "correctAnswers": [2], "explanation": { "en": "The controller monitors the battery's voltage to estimate its remaining life.", "vi": "Bộ điều khiển giám sát điện áp của pin để ước tính tuổi thọ còn lại của nó." } },
        { "id": "p4q15", "type": "single-select", "section": { "en": "Maintenance", "vi": "Bảo trì" }, "question": { "en": "When might the recommended replacement time for the grease be shorter than usual?", "vi": "Khi nào thời gian thay mỡ bôi trơn được khuyến nghị có thể ngắn hơn bình thường?" }, "options": [ { "en": "When the robot is used less frequently", "vi": "Khi robot được sử dụng ít thường xuyên hơn" }, { "en": "When the robot is stored in a dry environment", "vi": "Khi robot được bảo quản trong môi trường khô ráo" }, { "en": "When the robot is operated under heavy loads", "vi": "Khi robot hoạt động dưới tải nặng" }, { "en": "When the robot is operated in a cold environment", "vi": "Khi robot hoạt động trong môi trường lạnh" } ], "correctAnswers": [2], "explanation": { "en": "Operating under heavy loads, high duty cycles, or high speeds increases wear and requires more frequent greasing.", "vi": "Hoạt động dưới tải nặng, chu kỳ làm việc cao hoặc tốc độ cao làm tăng độ mòn và yêu cầu bôi trơn thường xuyên hơn." } }
    ],
    "part5": [
        { "id": "p5q1", "type": "fill-in", "image": "https://i.postimg.cc/BZTrmb5k/filltype-1.png", "alt": { "en": "Diagram of a 6-axis robot arm with parts numbered 1 to 5.", "vi": "Sơ đồ cánh tay robot 6 trục với các bộ phận được đánh số từ 1 đến 5." }, "question": { "en": "Write down the parts’ names in the below blank block. (1) to (5)", "vi": "Viết tên các bộ phận vào ô trống bên dưới. (1) đến (5)" }, "labels": [ { "id": 1, "correct": { "en": "Joint #6 Motor", "vi": "Động cơ trục #6" } }, { "id": 2, "correct": { "en": "LED Lamp", "vi": "Đèn LED" } }, { "id": 3, "correct": { "en": "Electromagnetic brake", "vi": "Phanh điện từ" } }, { "id": 4, "correct": { "en": "Reduction gear unit", "vi": "Bộ giảm tốc" } }, { "id": 5, "correct": { "en": "M/C Cable", "vi": "Cáp M/C" } } ] },
        { "id": "p5q2", "type": "fill-in", "image": "https://i.postimg.cc/y8tp1CXx/filltype-2.png", "alt": { "en": "System architecture diagram of RC180 controller and connected components, with parts numbered 1 to 5.", "vi": "Sơ đồ kiến trúc hệ thống của bộ điều khiển RC180 và các thành phần được kết nối, với các bộ phận được đánh số từ 1 đến 5." }, "question": { "en": "Write down the components/protocol/function in the below blank block. (1) to (5).", "vi": "Viết tên các thành phần/giao thức/chức năng vào ô trống bên dưới. (1) đến (5)." }, "labels": [ { "id": 1, "correct": { "en": "Expansion I/O Board", "vi": "Bo mạch I/O mở rộng" } }, { "id": 2, "correct": { "en": "Standard I/O, Remote I/O, Ethernet", "vi": "I/O tiêu chuẩn, I/O từ xa, Ethernet" } }, { "id": 3, "correct": { "en": "Driver Unit", "vi": "Bộ điều khiển" } }, { "id": 4, "correct": { "en": "USB 2.0 or Ethernet", "vi": "USB 2.0 hoặc Ethernet" } }, { "id": 5, "correct": { "en": "OP1", "vi": "OP1" } } ] }
    ],
    "part6": [
        { "id": "p6q1", "type": "ordering", "question": { "en": "Please describe the steps on how to backup and restore the controller’s file in RC+ software.", "vi": "Vui lòng mô tả các bước để sao lưu và phục hồi tệp của bộ điều khiển trong phần mềm RC+." }, "sub_questions": [ { "title": { "en": "Backup Procedure in RC+ Software", "vi": "Quy trình Sao lưu trong Phần mềm RC+" }, "steps": [ { "id": 0, "text": { "en": "Ensure the robot is in a safe state — task stopped and motor OFF.", "vi": "Đảm bảo robot ở trạng thái an toàn — tác vụ đã dừng và động cơ TẮT." } }, { "id": 1, "text": { "en": "Go to Tools → Controller.", "vi": "Đi tới Tools → Controller." } }, { "id": 2, "text": { "en": "Click Backup Controller.", "vi": "Nhấp vào Backup Controller." } }, { "id": 3, "text": { "en": "Select the storage drive and folder.", "vi": "Chọn ổ đĩa và thư mục lưu trữ." } }, { "id": 4, "text": { "en": "Click OK.", "vi": "Nhấp vào OK." } }, { "id": 5, "text": { "en": "The system backs up parameters, calibration data, project files, and global variables to the selected folder.", "vi": "Hệ thống sao lưu các thông số, dữ liệu hiệu chuẩn, tệp dự án và các biến toàn cục vào thư mục đã chọn." } }, { "id": 6, "text": { "en": "When completed without warnings or errors, the backup data is saved successfully.", "vi": "Khi hoàn tất mà không có cảnh báo hoặc lỗi, dữ liệu sao lưu được lưu thành công." } } ] }, { "title": { "en": "Restore Procedure in RC+ Software", "vi": "Quy trình Phục hồi trong Phần mềm RC+" }, "steps": [ { "id": 0, "text": { "en": "Ensure the robot is in a safe state — task stopped and motor OFF.", "vi": "Đảm bảo robot ở trạng thái an toàn — tác vụ đã dừng và động cơ TẮT." } }, { "id": 1, "text": { "en": "Go to Tools → Controller.", "vi": "Đi tới Tools → Controller." } }, { "id": 2, "text": { "en": "Click Restore Controller.", "vi": "Nhấp vào Restore Controller." } }, { "id": 3, "text": { "en": "Select the folder containing the backup data.", "vi": "Chọn thư mục chứa dữ liệu sao lưu." } }, { "id": 4, "text": { "en": "Choose the items to restore.", "vi": "Chọn các mục cần phục hồi." } }, { "id": 5, "text": { "en": "Click OK.", "vi": "Nhấp vào OK." } }, { "id": 6, "text": { "en": "After restoration, verify calibration, parameters, and projects. Restart the controller if necessary.", "vi": "Sau khi phục hồi, xác minh hiệu chuẩn, thông số và các dự án. Khởi động lại bộ điều khiển nếu cần thiết." } } ] } ] },
        { "id": "p6q2", "type": "ordering", "question": { "en": "When Error 9716 occurs, what actions should you take?", "vi": "Khi xảy ra Lỗi 9716, bạn nên thực hiện những hành động nào?" }, "sub_questions": [ { "title": { "en": "(1) How to confirm which parts probably have a problem?", "vi": "(1) Làm cách nào để xác nhận bộ phận nào có thể có vấn đề?" }, "steps": [ { "id": 0, "text": { "en": "Check that the BT connector (battery connector) is securely attached.", "vi": "Kiểm tra xem đầu nối BT (đầu nối pin) có được gắn chắc chắn không." } }, { "id": 1, "text": { "en": "Make sure the battery voltage is at least 3.6 volts.", "vi": "Đảm bảo điện áp pin ít nhất là 3.6 volt." } } ] }, { "title": { "en": "(2) How to recover, what actions you will take?", "vi": "(2) Làm cách nào để phục hồi, bạn sẽ thực hiện những hành động nào?" }, "steps": [ { "id": 0, "text": { "en": "First, reset the encoder.", "vi": "Đầu tiên, đặt lại bộ mã hóa." } }, { "id": 1, "text": { "en": "Then, reboot the controller.", "vi": "Sau đó, khởi động lại bộ điều khiển." } }, { "id": 2, "text": { "en": "Finally, perform zero pulse position calibration.", "vi": "Cuối cùng, thực hiện hiệu chuẩn vị trí xung zero." } } ] } ] },
        { "id": "p6q3", "type": "ordering", "question": { "en": "Please describe the pulse zero calibration procedure for the 6-axis robot.", "vi": "Vui lòng mô tả quy trình hiệu chuẩn xung zero cho robot 6 trục." }, "sub_questions": [ { "title": { "en": "1. Power On and Zero the Joints", "vi": "1. Bật nguồn và Đưa các khớp về Zero" }, "steps": [ { "id": 0, "text": { "en": "First, turn on the servo motor (S Motor).", "vi": "Đầu tiên, bật động cơ servo (S Motor)." } }, { "id": 1, "text": { "en": "Then, bring all joints to their zero position (Use jog function or manually adjust).", "vi": "Sau đó, đưa tất cả các khớp về vị trí zero của chúng (Sử dụng chức năng jog hoặc điều chỉnh thủ công)." } } ] }, { "title": { "en": "2. Enter Calibration Commands", "vi": "2. Nhập lệnh Hiệu chuẩn" }, "steps": [ { "id": 0, "text": { "en": "In the command window, input the command: calpls 0,0,0,0,0,0", "vi": "Trong cửa sổ lệnh, nhập lệnh: calpls 0,0,0,0,0,0" } }, { "id": 1, "text": { "en": "Next, input the command: Calib 1,2,3,4,5,6", "vi": "Tiếp theo, nhập lệnh: Calib 1,2,3,4,5,6" } } ] } ] }
    ]
};


export const translations: Record<string, Record<string, string>> = {
    en: {
        app_title: "Robot Midterm Exam Review",
        app_subtitle: "Choose a mode to start",
        study_mode: "Study Mode",
        test_mode: "Take a Test",
        back_to_menu: "Back to Menu",
        submit_button: "Submit",
        results_title: "Results",
        restart_button: "Restart",
        part1_title: "Part I: General",
        part2_title: "Part II: Hardware and Coordinates",
        part3_title: "Part III: Programming",
        part4_title: "Part IV: 15 Questions",
        part5_title: "Part V: Fill-in Quiz",
        part6_title: "Part VI: Essay Quiz",
        explanation_title: "Explanation",
        your_answer: "Your answer",
        correct_answer: "Correct answer",
        correct: "Correct",
        incorrect: "Incorrect",
        score_prefix: "You scored",
        score_suffix: "out of",
    },
    vi: {
        app_title: "Ôn thi Robot Midterm",
        app_subtitle: "Chọn chế độ để bắt đầu",
        study_mode: "Chế độ Học",
        test_mode: "Làm Kiểm tra",
        back_to_menu: "Về Menu",
        submit_button: "Nộp bài",
        results_title: "Kết quả",
        restart_button: "Làm lại",
        part1_title: "Phần I: Tổng quan",
        part2_title: "Phần II: Phần cứng và Tọa độ",
        part3_title: "Phần III: Lập trình",
        part4_title: "Phần IV: 15 Câu hỏi",
        part5_title: "Phần V: Câu hỏi điền vào chỗ trống",
        part6_title: "Phần VI: Câu hỏi Tự luận",
        explanation_title: "Giải thích",
        your_answer: "Câu trả lời của bạn",
        correct_answer: "Đáp án đúng",
        correct: "Đúng",
        incorrect: "Sai",
        score_prefix: "Bạn đạt",
        score_suffix: "trên tổng",
    }
};

let allQuestions: Question[] | null = null;

export const getAllQuestions = (): Question[] => {
    if (allQuestions) {
        return allQuestions;
    }
    
    const flattenedQuestions = Object.entries(quizData).flatMap(([partKey, questions]) => 
        (questions as any[]).map(q => ({ ...q, part: partKey }))
    );

    allQuestions = flattenedQuestions as Question[];
    return allQuestions;
};
